# Generated by Django 4.1.3 on 2022-11-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
